import fillpdf
from fillpdf import fillpdfs

text = fillpdfs.get_form_fields("form.pdf", sort=False, page_number=None)
print(text)
data_dict = {'SVP Name': 'BRIANNA GUTTMAN',
            'Primary Insured': None,
            'Primary DOB Month': None,
            'Primary DOB Date': None,
            'Primary DOB Year': None,
            'Gender 1': None,
            'Primary Phone': None,
            'Second Insured': None,
            'Secondary DOB Month': None,
            'Secondary DOB Date': None,
            'Secondary DOB Year': None,
            'Gender 2': None,
            'Secondary Phone': None,
            'Address': None,
            'Cit y': None,
            'State': None,
            'Email Address': None,
            'NotesT ravel Hobbies Language etc': None,
            'T ime': None,
            'Date': None,
            'M on': 'On',
            'T ues': 'On',
            'Weds': 'On',
            'Thurs': 'On',
            'Fri': 'On',
            'T ime_2': None,
            'Date_2': None,
            'M on_2': 'On',
            'T ues_2': 'On',
            'Weds_2': 'On',
            'Thurs_2': 'On',
            'Fri_2': 'On',
            'Home': 'On',
            'Indicate Hour AM or PM 15 m inute time fra mes p lease': 'Off',
            'Work': 'On',
            'Other': None,
            'S pecial Instructions': None,
            'Carrier': None,
            'Face Amount': None,
            'Product': None,
            'Prop osed Premium': None,
            'Annual': 'On',
            'M onthly': 'On',
            'Quart erly': 'On',
            'SemiAnnual': 'On',
            'Stat e of Issue': None,
            '10 Year': 'On',
            '15 Year': '',
            '20 Year': 'On',
            '25 Year': 'On',
            '30 Year': 'On',
            'ROP Check': 'On',
            'ROP': None,
            'Rate Class quot ed': None,
            'Universal Life': 'On',
            'Whole Life': 'On',
            'Index UL': 'On',
            'Variable Life': 'On',
            'LTC Rider': 'On',
            'Last Survivor': 'On',
            'Will new insurance replace any inforce i nsurance': None,
            'Financial Advisor Name': 'SCOTT SUMMERLIN',
            'Firm': 'PFG',
            'Email': 'SCOTT@STARLIFTERWEALTH.COM',
            'Branch City': 'BOISE',
            'Business Phone 123': '208',
            'Business Phone 456': '841',
            'Business Phone 78910': '5678',
            'Licensed in': 'ID',
            'Licensed in State of Insured': 'Yes_2',
            'Advisor Appointed with Carrier & PSF': None,
            'Date_3': None,
            'Zip Code': None,
            'Trust to be established': '',
            'Text Field0': None,
            'Ownership': '',}


fillpdfs.write_fillable_pdf('form.pdf', 'new.pdf', data_dict)