import fillpdf
from fillpdf import fillpdfs

text = fillpdfs.get_form_fields("form.pdf", sort=False, page_number=None)
print(text)
data_dict = {'SVP Name': 'BRIANNA GUTTMAN',
            'Primary Insured': 'John Doe',
            'Primary DOB Month': 'January',
            'Primary DOB Date': '1',
            'Primary DOB Year': '1990',
            'Gender 1': 'Male 1',
            'Primary Phone': '123-456-7890',
            'Second Insured': 'Jane Doe',
            'Secondary DOB Month': 'February',
            'Secondary DOB Date': '2',
            'Secondary DOB Year': '1995',
            'Gender 2': 'Female 2',
            'Secondary Phone': '987-654-3210',
            'Address': '123 Main Street',
            'City': 'Anytown',
            'State': 'California',
            'Email Address': 'johndoe@example.com',
            'Notes Travel Hobbies Language etc': 'Enjoys traveling and playing guitar',
            'Time': '10:00 AM',
            'Date': 'March 1, 2024',
            'Mon': 'On',
            'Tues': 'On',
            'Weds': 'On',
            'Thurs': 'On',
            'Fri': 'On',
            'Time_2': '2:00 PM',
            'Date_2': 'March 3, 2024',
            'Mon_2': 'On',
            'Tues_2': 'On',
            'Weds_2': 'On',
            'Thurs_2': 'On',
            'Fri_2': 'On',
            'Home': 'On',
            'Indicate Hour AM or PM 15 minute time frames please': 'AM',
            'Work': 'On',
            'Other': 'None',
            'Special Instructions': 'Please contact via email',
            'Carrier': 'XYZ Insurance',
            'Face Amount': '$500,000',
            'Product': 'Term Life Insurance',
            'Proposed Premium': '$50',
            'Annual': 'On',
            'Monthly': 'On',
            'Quarterly': 'On',
            'SemiAnnual': 'On',
            'State of Issue': 'California',
            '10 Year': 'On',
            '15 Year': 'On',
            '20 Year': 'On',
            '25 Year': 'On',
            '30 Year': 'On',
            'ROP Check': 'On',
            'ROP': 'None',
            'Rate Class quoted': 'Preferred',
            'Universal Life': 'On',
            'Whole Life': 'On',
            'Index UL': 'On',
            'Variable Life': 'On',
            'LTC Rider': 'On',
            'Last Survivor': 'On',
            'Will new insurance replace any inforce insurance': 'No',
            'Financial Advisor Name': 'SCOTT SUMMERLIN',
            'Firm': 'PFG',
            'Email': 'scott@starlifterwealth.com',
            'Branch City': 'Boise',
            'Business Phone 123': '208',
            'Business Phone 456': '841',
            'Business Phone 78910': '5678',
            'Licensed in': 'ID',
            'Licensed in State of Insured': 'Yes_2',
            'Advisor Appointed with Carrier & PSF': 'None',
            'Date_3': 'None',
            'Zip Code': '12345',
            'Trust to be established': 'None',
            'Text Field0': 'None',
            'Ownership': 'Individual',}


fillpdfs.write_fillable_pdf('form.pdf', 'new.pdf', data_dict)